FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MusicMaster

Music information at your finger tips

## Albums [/albums]

### List All Albums [GET]

+ Response 200 (application/json)

        [
            {
                "albums": [
                    {
                        "Name": "Depths Of the Ocean",
                        "Artist": "Sushmit Sen"
                    }]
            }
        ]